In [1]:
import numpy as np

In [2]:
A = np.random.randn(14, 10)
B = np.random.randn(14, 10)
C = np.random.randn(10, 14)

# A@B is not valid

np.shape(C@B)
np.shape(B@C)

(14, 14)

In [3]:
def matrixMultiplication(A, B):

    # get matrix sizes
    size_A = np.shape(A)
    size_B = np.shape(B)

    # check sizes and give error (if multiplication is not valid)
    if size_A[1] != size_B[0]:
        raise ValueError("Inner dimensions don't match")
    
    # initialize
    C = np.zeros((size_A[0], size_B[1]))

    # compute
    for i in range(size_A[0]):
        for j in range(size_B[1]):
            C[i, j] = np.dot(A[i, :], B[:, j])
    
    return C

In [4]:
A = np.random.randn(4, 6)
B = np.random.randn(6, 4)

C1 = matrixMultiplication(A, B)

C2 = A@B

print(C1)
print(C1 - C2)

[[-0.76781292 -2.6648828  -3.65506659 -7.32973708]
 [-0.23283435 -2.8077352  -3.60734815 -5.15434975]
 [-3.24539329 -7.20406214  0.74101486 -0.47913463]
 [-2.01001423 -3.96694438 -0.11504148  1.00547852]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
A = np.random.randn(4, 6)
B = np.random.randn(4, 4)

C = matrixMultiplication(A, B)

ValueError: Inner dimensions don't match